#!/usr/bin/env python3
"""
키워드 한글 → 영어 변환 스크립트
"""

import sys
from pathlib import Path

# 프로젝트 루트를 Python 경로에 추가
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

import sqlite3
from src.core.database import Database

# 키워드 번역 맵
KEYWORD_TRANSLATION_MAP = {
    "AI": "AI",
    "머신러닝": "Machine Learning",
    "딥러닝": "Deep Learning",
    "데이터": "Data",
    "모델(Model)": "Model",
    "알고리즘": "Algorithm",
    "훈련(Training)": "Training",
    "테스트(Test)": "Test",
    "검증(Validation)": "Validation",
    "오버피팅": "Overfitting",
    "언더피팅": "Underfitting",
    "일반화": "Generalization",
    "피처(Feature)": "Feature",
    "라벨(Label)": "Label",
    "데이터셋": "Dataset",
    "샘플": "Sample",
    "편향(Bias)": "Bias",
    "분산(Variance)": "Variance",
    "하이퍼파라미터": "Hyperparameter",
    "손실함수": "Loss Function",
    "정확도": "Accuracy",
    "정밀도": "Precision",
    "재현율": "Recall",
    "F1 스코어": "F1 Score",
    "혼동행렬": "Confusion Matrix",
    "파라미터": "Parameter",
    "에폭(Epoch)": "Epoch",
    "배치(Batch)": "Batch",
    "확률": "Probability",
    "통계적 추정": "Statistical Estimation",
    "지도학습": "Supervised Learning",
    "비지도학습": "Unsupervised Learning",
    "강화학습": "Reinforcement Learning",
    "회귀": "Regression",
    "분류": "Classification",
    "의사결정나무": "Decision Tree",
    "랜덤포레스트": "Random Forest",
    "부스팅": "Boosting",
    "그라디언트 부스팅": "Gradient Boosting",
    "XGBoost": "XGBoost",
    "SVM": "SVM",
    "KNN": "KNN",
    "k-means": "k-means",
    "PCA": "PCA",
    "차원 축소": "Dimensionality Reduction",
    "군집화": "Clustering",
    "이상치 탐지": "Outlier Detection",
    "엔트로피": "Entropy",
    "지니계수": "Gini Coefficient",
    "학습률": "Learning Rate",
    "교차검증": "Cross Validation",
    "그리드서치": "Grid Search",
    "모델 평가": "Model Evaluation",
    "피처 엔지니어링": "Feature Engineering",
    "표준화": "Standardization",
    "정규화": "Normalization",
    "원-핫 인코딩": "One-Hot Encoding",
    "Binning": "Binning",
    "샘플링": "Sampling",
    "언더샘플링": "Undersampling",
    "오버샘플링": "Oversampling",
    "SMOTE": "SMOTE",
    "선형회귀": "Linear Regression",
    "로지스틱회귀": "Logistic Regression",
    "ROC 커브": "ROC Curve",
    "AUC": "AUC",
    "성능 지표": "Performance Metrics",
    "연관 규칙": "Association Rules",
    "Apriori": "Apriori",
    "시간 시리즈": "Time Series",
    "예측 모델": "Prediction Model",
    "이동평균": "Moving Average",
    "ARIMA": "ARIMA",
    "리스크 모델링": "Risk Modeling",
    "모델 해석성": "Model Interpretability",
    "SHAP": "SHAP",
    "LIME": "LIME",
    "피처 중요도": "Feature Importance",
    "모델 드리프트": "Model Drift",
    "MLOps": "MLOps",
    "뉴런": "Neuron",
    "퍼셉트론": "Perceptron",
    "활성화 함수": "Activation Function",
    "ReLU": "ReLU",
    "Sigmoid": "Sigmoid",
    "Softmax": "Softmax",
    "신경망(NN)": "Neural Network",
    "딥 뉴럴 네트워크(DNN)": "Deep Neural Network",
    "순전파": "Forward Propagation",
    "역전파": "Backpropagation",
    "손실 감소": "Loss Reduction",
    "경사하강법": "Gradient Descent",
    "최적화 알고리즘": "Optimization Algorithm",
    "Adam": "Adam",
    "SGD": "SGD",
    "배치 정규화": "Batch Normalization",
    "드롭아웃": "Dropout",
    "Convolution": "Convolution",
    "CNN": "CNN",
    "Max pooling": "Max Pooling",
    "Feature map": "Feature Map",
    "필터": "Filter",
    "파라미터 공유": "Parameter Sharing",
    "이미지 분류": "Image Classification",
    "Object Detection": "Object Detection",
    "YOLO": "YOLO",
    "R-CNN": "R-CNN",
    "ResNet": "ResNet",
    "Skip connection": "Skip Connection",
    "VGG": "VGG",
    "전이학습": "Transfer Learning",
    "Fine-tuning": "Fine-tuning",
    "데이터 증강": "Data Augmentation",
    "Flatten": "Flatten",
    "Fully Connected Layer": "Fully Connected Layer",
    "Autoencoder": "Autoencoder",
    "VAE": "VAE",
    "GAN": "GAN",
    "Generator": "Generator",
    "Discriminator": "Discriminator",
    "Latent space": "Latent Space",
    "Attention": "Attention",
    "Encoder": "Encoder",
    "Decoder": "Decoder",
    "Transformer": "Transformer",
    "Self-attention": "Self-Attention",
    "Positional encoding": "Positional Encoding",
    "Multi-head attention": "Multi-Head Attention",
    "Layer normalization": "Layer Normalization",
    "BERT": "BERT",
    "GPT": "GPT",
    "Embedding": "Embedding",
    "Token": "Token",
    "토크나이저": "Tokenizer",
    "Masked Language Model": "Masked Language Model",
    "Next Token Prediction": "Next Token Prediction",
    "RNN": "RNN",
    "LSTM": "LSTM",
    "GRU": "GRU",
    "Seq2Seq": "Seq2Seq",
    "텍스트 전처리": "Text Preprocessing",
    "토큰화": "Tokenization",
    "스톱워드": "Stop Words",
    "표제어 추출": "Lemmatization",
    "형태소 분석": "Morphological Analysis",
    "단어 임베딩": "Word Embedding",
    "Word2Vec": "Word2Vec",
    "GloVe": "GloVe",
    "TF-IDF": "TF-IDF",
    "문장 임베딩": "Sentence Embedding",
    "Semantic similarity": "Semantic Similarity",
    "챗봇": "Chatbot",
    "질의응답(QA)": "Question Answering",
    "요약": "Summarization",
    "번역 모델": "Translation Model",
    "감성 분석": "Sentiment Analysis",
    "Named Entity Recognition": "Named Entity Recognition",
    "문장 분류": "Sentence Classification",
    "문맥": "Context",
    "Zero-shot": "Zero-shot",
    "Few-shot": "Few-shot",
    "Prompt": "Prompt",
    "Prompt tuning": "Prompt Tuning",
    "Instruction tuning": "Instruction Tuning",
    "RLHF": "RLHF",
    "안전성": "Safety",
    "편향 제거": "Bias Removal",
    "토큰 제한": "Token Limit",
    "컨텍스트 길이": "Context Length",
    "RAG": "RAG",
    "Vector DB": "Vector Database",
    "임베딩 검색": "Embedding Search",
    "LLM 파인튜닝": "LLM Fine-tuning",
    "LoRA": "LoRA",
    "Quantization": "Quantization",
    "하이브리드 검색": "Hybrid Search",
    "온톨로지": "Ontology",
    "지식 그래프": "Knowledge Graph",
    "자연어 생성(NLG)": "Natural Language Generation",
    "문장 재구성": "Sentence Reconstruction",
    "문맥적 의미": "Contextual Meaning",
    "프롬프트 패턴": "Prompt Pattern",
    "체인 오브 쏘트": "Chain of Thought",
    "소크래틱 프롬프트": "Socratic Prompt",
    "Tool use": "Tool Use",
    "Function calling": "Function Calling",
    "멀티모달 모델": "Multimodal Model",
    "시각-Language 모델(VLM)": "Vision-Language Model",
    "TTS": "TTS",
    "STT": "STT",
    "문장 토큰 확률": "Token Probability",
    "hallucination": "Hallucination",
    "grounding": "Grounding",
    "데이터 정합성": "Data Consistency",
    "문장 구조": "Sentence Structure",
    "의미 네트워크": "Semantic Network",
    "문서 임베딩": "Document Embedding",
    "Retrieval": "Retrieval",
    "문서 요약": "Document Summarization",
    "데이터 파이프라인": "Data Pipeline",
    "ETL": "ETL",
    "데이터 전처리": "Data Preprocessing",
    "정제(cleaning)": "Data Cleaning",
    "이상치 처리": "Outlier Handling",
    "결측치 처리": "Missing Value Handling",
    "데이터 품질": "Data Quality",
    "로그 데이터": "Log Data",
    "스트리밍 데이터": "Streaming Data",
    "빅데이터": "Big Data",
    "Hadoop": "Hadoop",
    "Spark": "Spark",
    "데이터 웨어하우스": "Data Warehouse",
    "데이터 레이크": "Data Lake",
    "파케(parquet)": "Parquet",
    "인덱스": "Index",
    "SQL": "SQL",
    "NoSQL": "NoSQL",
    "Redis": "Redis",
    "캐싱": "Caching",
    "API": "API",
    "API 호출": "API Call",
    "JSON": "JSON",
    "CSV": "CSV",
    "스키마": "Schema",
    "데이터 카탈로그": "Data Catalog",
    "버전 관리": "Version Control",
    "Git": "Git",
    "GitHub": "GitHub",
    "CI/CD": "CI/CD",
    "파이프라인 자동화": "Pipeline Automation",
    "Docker": "Docker",
    "컨테이너": "Container",
    "Kubernetes": "Kubernetes",
    "배포": "Deployment",
    "추론 서버": "Inference Server",
    "서버리스": "Serverless",
    "GPU": "GPU",
    "TPU": "TPU",
    "연산 최적화": "Computational Optimization",
    "메모리 관리": "Memory Management",
    "지연시간 latency": "Latency",
    "Throughput": "Throughput",
    "Scale-out": "Scale-out",
    "Scale-up": "Scale-up",
    "로드밸런싱": "Load Balancing",
    "캐시 미스": "Cache Miss",
    "모델 서빙": "Model Serving",
    "A/B 테스트": "A/B Testing",
    "Canary 배포": "Canary Deployment",
    "모델 모니터링": "Model Monitoring",
    "데이터 드리프트": "Data Drift",
    "로그 분석": "Log Analysis",
    "백엔드": "Backend",
    "프론트엔드": "Frontend",
    "REST API": "REST API",
    "GraphQL": "GraphQL",
    "Node.js": "Node.js",
    "Python": "Python",
    "Streamlit": "Streamlit",
    "AI 전략": "AI Strategy",
    "AI ROI": "AI ROI",
    "AI 도입 절차": "AI Implementation",
    "AI 윤리": "AI Ethics",
    "개인정보 보호": "Privacy Protection",
    "데이터 보안": "Data Security",
    "AI 리스크 관리": "AI Risk Management",
    "자동화": "Automation",
    "RPA": "RPA",
    "챗봇 자동화": "Chatbot Automation",
    "문서 자동화": "Document Automation",
    "업무 프로세스 분석": "Business Process Analysis",
    "워크플로우": "Workflow",
    "지식 관리": "Knowledge Management",
    "디지털 트윈": "Digital Twin",
    "예측 유지보수": "Predictive Maintenance",
    "산업용 AI": "Industrial AI",
    "의료 AI": "Medical AI",
    "금융 AI": "Financial AI",
    "리스크 스코어링": "Risk Scoring",
    "추천 시스템": "Recommendation System",
    "필터링": "Filtering",
    "협업 필터링": "Collaborative Filtering",
    "콘텐츠 기반 추천": "Content-Based Recommendation",
    "개인화": "Personalization",
    "고객 세그먼트": "Customer Segmentation",
    "데이터 기반 마케팅": "Data-Driven Marketing",
    "A/B 실험": "A/B Experiment",
    "CRM": "CRM",
    "광고 타게팅": "Ad Targeting",
    "서치 엔진": "Search Engine",
    "SEO": "SEO",
    "대규모 데이터 처리": "Large-Scale Data Processing",
    "Fraud detection": "Fraud Detection",
    "Price optimization": "Price Optimization",
    "수요 예측": "Demand Forecasting",
    "공급망 최적화": "Supply Chain Optimization",
    "물류 최적화": "Logistics Optimization",
    "AI 제품 기획": "AI Product Planning",
    "PMF": "PMF",
    "UX": "UX",
    "사용자 연구": "User Research",
    "AI 활용도 분석": "AI Utilization Analysis",
    "KPI 설정": "KPI Setting",
    "AI 플랫폼": "AI Platform",
    "LLMOps": "LLMOps",
    "AI Product": "AI Product",
    "Agent": "Agent",
    "Multi-agent system": "Multi-Agent System",
    "Tool agent": "Tool Agent",
    "Planning": "Planning",
    "Reasoning": "Reasoning",
    "Chain-of-thought": "Chain-of-Thought",
    "Self-reflection": "Self-Reflection",
    "Debate": "Debate",
    "Memory": "Memory",
    "Agent 평가": "Agent Evaluation",
    "Agent 자동화": "Agent Automation",
    "AI 컴패니언": "AI Companion",
    "AI 코치": "AI Coach",
    "AI 튜터": "AI Tutor",
    "생산성 향상": "Productivity Enhancement",
    "업무 자동화 프롬프트": "Workflow Automation Prompt",
    "데이터 활용 전략": "Data Utilization Strategy",
    "사용자 흐름": "User Flow",
    "AI 기반 분석": "AI-Based Analysis",
    "인사이트 도출": "Insight Extraction",
    "실험 설계": "Experimental Design",
    "AI 윤리 가이드": "AI Ethics Guide",
    "AI 책임성": "AI Accountability",
    "초거대 모델": "Large Language Model",
    "Scaling law": "Scaling Law",
    "Sparse attention": "Sparse Attention",
    "Mixture-of-Experts": "Mixture-of-Experts",
    "Distillation": "Distillation",
    "Alignment": "Alignment",
    "오픈웨이트 모델": "Open Weight Model",
    "프라이버시 강화 학습": "Privacy-Preserving Learning",
    "차등 프라이버시": "Differential Privacy",
    "경량화 모델": "Lightweight Model",
    "지식 증류": "Knowledge Distillation",
    "AutoML": "AutoML",
    "Neural Architecture Search": "Neural Architecture Search",
    "신경망 압축": "Neural Network Compression",
    "Edge AI": "Edge AI",
    "온디바이스 AI": "On-Device AI",
    "멀티모달 추론": "Multimodal Reasoning",
    "World model": "World Model",
    "Self-supervised learning": "Self-Supervised Learning",
    "Contrastive learning": "Contrastive Learning",
    "분산 AI": "Distributed AI",
    "협업 AI": "Collaborative AI",
    "시뮬레이션 학습": "Simulation Learning",
    "비선형성": "Non-linearity",
    "불확실성 정량화": "Uncertainty Quantification",
    "베이지안 추론": "Bayesian Inference",
    "의사결정 모델": "Decision Model",
    "Explainable AI": "Explainable AI",
    "Responsible AI": "Responsible AI",
    "AGI": "AGI",
    "AI 안전 연구": "AI Safety Research",
    "휴먼 인 더 루프": "Human-in-the-Loop",
    "모델 감시": "Model Monitoring",
    "신뢰성": "Reliability",
    "AI의 미래": "Future of AI",
}


def translate_keywords():
    """모든 한글 키워드를 영어로 변환"""
    db = Database()
    conn = db._get_connection()
    cursor = conn.cursor()
    
    # 모든 키워드 가져오기
    cursor.execute("SELECT id, keyword FROM keywords ORDER BY sequence_number")
    keywords = cursor.fetchall()
    
    print(f"📝 총 {len(keywords)}개 키워드 발견\n")
    
    updated_count = 0
    skipped_count = 0
    
    for row in keywords:
        keyword_id = row[0]
        old_keyword = row[1]
        
        # 번역 맵에 있는 경우만 변환
        if old_keyword in KEYWORD_TRANSLATION_MAP:
            new_keyword = KEYWORD_TRANSLATION_MAP[old_keyword]
            
            # 키워드 업데이트
            try:
                cursor.execute(
                    "UPDATE keywords SET keyword = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
                    (new_keyword, keyword_id)
                )
                print(f"✅ {old_keyword} → {new_keyword}")
                updated_count += 1
            except sqlite3.IntegrityError as e:
                # 중복 키워드인 경우
                print(f"⚠️  {old_keyword} → {new_keyword} (중복, 스킵)")
                skipped_count += 1
        else:
            # 이미 영어이거나 번역 맵에 없는 경우
            print(f"⏭️  {old_keyword} (변환 불필요 또는 번역 맵 없음)")
            skipped_count += 1
    
    conn.commit()
    conn.close()
    
    print(f"\n{'='*60}")
    print(f"✅ 변환 완료!")
    print(f"   - 변환됨: {updated_count}개")
    print(f"   - 스킵됨: {skipped_count}개")
    print(f"{'='*60}")


if __name__ == '__main__':
    translate_keywords()

